services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5-r0-ls183
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - MYSQL_ROOT_PASSWORD= # put root password here
      - MYSQL_DATABASE=      # put user database name here
      - MYSQL_USER=          # put user name here
      - MYSQL_PASSWORD=      # put user password here
    volumes:
      - ./mariadb_config:/config
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:5.2.2-ls191
    container_name: phpmyadmin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - PMA_ARBITRARY=1 
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    volumes:
      - ./phpmyadmin_config:/config
    ports:
      - 8000:80
    restart: unless-stopped
    depends_on:
      - mariadb

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    environment:
      MINIO_ROOT_USER:       # put root user name here
      MINIO_ROOT_PASSWORD:   # put root password here
    volumes:
      - minio_data:/data 
      - minio_config:/root/.minio 
    ports:
      - 9000:9000 # MinIO API port
      - 9001:9001 # MinIO Console port (for browser access)
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data: 
  minio_config: 
  mariadb_data: 
